### ISSUE TITLE
coinbase name conflict with https://github.com/sibblegp/coinbase_python

### ISSUE THREAD

**Issue by sylvainblot** [eldarion/django-coinbase#5]
Are you ok to rename the package to django-coinbase ? If so I will provide a pull request.

**Comment by paltman** [comment]
@sylvainblot I really don't see using both packages at the same time. Are you currently using both at the same time? Can you explain your use case?

**Comment by sylvainblot** [comment]
@paltman better now than never. I use the API to create buttons. Meanwhile Django 1.7 introduce AppConfig that let me change the module name at runtime.

Example apps.py:

```
from django.apps import AppConfig

class CoinbaseAppConfig(AppConfig):
    label = "django_coinbase"
    name = "coinbase"
```

**Comment by paltman** [comment]
Cool!
